# Data Audit 
[Next Notebook](preprocessing.ipynb)

Before I do any manipulation to the data such as preprocessing and train/validate/test splits, I need to audit the dataset to gain more insight into features, the target and metrics.

I would recommend running all code cells before reading.

## The Dataset
The following shows the first 5 rows of the dataset

In [37]:
import pandas as pd

Teen_Mental_Health_Dataset = pd.read_csv('../data/Teen_Mental_Health_Dataset.csv');
display(Teen_Mental_Health_Dataset.head())

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0

## Columns
The following is some information about the columns of the dataset

### Metrics

In [38]:
display(Teen_Mental_Health_Dataset.describe())

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,15.928333,4.536667,6.449417,1.740333,2.990383,1.014500,5.445833,5.636667,5.565000,0.025833
std,2.021947,2.029599,1.442677,0.716660,0.576758,0.582185,2.903290,2.859453,2.830627,0.158704
min,13.000000,1.000000,4.000000,0.500000,2.000000,0.000000,1.000000,1.000000,1.000000,0.000000
25%,14.000000,2.800000,5.200000,1.100000,2.500000,0.500000,3.000000,3.000000,3.000000,0.000000
50%,16.000000,4.500000,6.500000,1.800000,2.990000,1.000000,5.000000,6.000000,6.000000,0.000000
75%,18.000000,6.300000,7.600000,2.400000,3.480000,1.500000,8.000000,8.000000,8.000000,0.000000
max,19.000000,8.000000,9.000000,3.000000,4.000000,2.000000,10.000000,10.000000,10.000000,1.000000

### Column info
The data is already quite clean; there are no duplicate rows and no null entries. No need for imputing

In [39]:
display(Teen_Mental_Health_Dataset.info())

display(pd.DataFrame({
  "duplicate rows": Teen_Mental_Health_Dataset.duplicated().sum()
}, index=["count"]).transpose())

display(pd.DataFrame({
  "data type": Teen_Mental_Health_Dataset.dtypes,
  "count": Teen_Mental_Health_Dataset.count(),
  "unique": Teen_Mental_Health_Dataset.nunique(),
  "null": Teen_Mental_Health_Dataset.isnull().sum()
}))

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   str
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   str
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   str
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
dtypes: float64(5), int64(5), str(3)
memory usage: 122.0 KB

None

                count
duplicate rows      0

                         data type  count  unique  null
age                          int64   1200       7     0
gender                         str   1200       2     0
daily_social_media_hours   float64   1200      71     0
platform_usage                 str   1200       3     0
sleep_hours                float64   1200      51     0
screen_time_before_sleep   float64   1200      26     0
academic_performance       float64   1200     201     0
physical_activity          float64   1200      21     0
social_interaction_level       str   1200       3     0
stress_level                 int64   1200      10     0
anxiety_level                int64   1200      10     0
addiction_level              int64   1200      10     0
depression_label             int64   1200       2     0

### Target
The target of this portfolio is `depression_label`

In [40]:
depressed = lambda x: Teen_Mental_Health_Dataset.loc[(Teen_Mental_Health_Dataset.depression_label == 0) ^ x].count()["depression_label"]

display(pd.DataFrame({
  "depression_label = true": depressed(True),
  "depression_label = false": depressed(False)
}, index=["count"]).transpose())

                          count
depression_label = true      31
depression_label = false   1169

As you can see, over 97% of the rows have a false depression label, however this does not render the dataset unusable. I now know that i need to avoid `accuracy` as a metric because i would expect around 97% accuracy for even a baseline model, instead i should look at `recall`, `precision` or combine the 2 using their harmonic mean `f1`. Since the number of positive cases is quite low, stratifying the dataset for things like cross validation may be difficult.

Lastly, I will give the binary representation of `depression_label` a categorical label so that it is easier to interpret, and save the dataset to the notebook store to access in other notebooks

In [41]:
Teen_Mental_Health_Dataset["depression_label"] = Teen_Mental_Health_Dataset["depression_label"].apply(
    lambda x: "depressed" if x == 1 else "not depressed"
)

%store Teen_Mental_Health_Dataset

Stored 'Teen_Mental_Health_Dataset' (DataFrame)

## [Go to the next notebook](preprocessing.ipynb)