In [1]:
import pandas as pd
df = pd.read_csv('../data/instagram_data.csv')

df

,reel_id,creator_id,creator_followers,posting_time,reel_length_sec,hook_strength_score,caption_length,hashtags_count,trending_audio,audio_popularity_score,...,likes,comments,shares,saves,engagement_rate,impressions,reach,non_follower_reach_ratio,explore_page_boost,virality_score
0,c437715e-d1e4-4f40-8548-8718243c6516,70c2ca5a-9d3a-4ba0-9aed-62cdbbc1663f,4208388,3,31,0.451657,0,20,True,0.399659,...,779301,30002,16741,21305,0.884296,75968410,39007279,0.960121,False,82.843160
1,9097bb11-0e03-4360-a239-6613ed2025df,b6bb4240-6341-47ce-bdd4-86fcba18d9ad,4096880,4,38,0.988437,205,2,False,0.294848,...,482481,49717,10095,19802,0.609125,90722120,84132612,0.909716,False,60.256519
2,a8e09994-3314-400b-9f3a-683b494f1070,7902b14d-cb95-4673-8ef1-482ff5151801,2624351,0,13,0.019949,205,6,True,0.697575,...,925249,12046,13883,13444,0.057583,75215994,82019789,0.101694,True,0.483295
3,afafb1c3-90c4-4918-8910-3a2338a812c5,3878d999-6087-4a40-a59e-45abe8978736,437778,23,15,0.564485,292,1,False,0.271352,...,633556,37062,5290,245,0.927607,32759775,89513213,0.900505,False,21.686033
4,dcb1e68c-79ba-4808-bf74-d102fa68a526,4077faf8-bc0c-42df-b060-f90d074e8e01,4388903,3,30,0.556782,215,27,False,0.757624,...,55799,16634,5733,19235,0.723132,12315042,25073380,0.589176,True,46.046599
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1955a53c-eab3-4393-b861-dd2794b104c6,4c664f20-bdde-4af2-b36a-31c7b9da70d0,3946383,18,51,0.351408,298,9,False,0.373963,...,461163,4067,17053,26663,0.778867,92834444,47248377,0.484767,False,89.025863
99996,9eab5220-f357-4644-bed7-19139c9dea50,58d5c005-7989-4e85-9c9f-506b3e2e8f6d,4314894,22,39,0.094755,83,16,False,0.248058,...,730977,30383,29848,25567,0.289401,79691074,91497041,0.360169,False,86.450634
99997,02e1f63b-deb5-4f1d-bcee-7c8fb1669b17,264fb15b-9799-4b3e-9576-6130a09e9923,1198854,10,33,0.867385,182,26,True,0.077438,...,648998,36116,29009,10461,0.369611,99281430,20412833,0.408280,True,43.480384
99998,f33b38e6-ec18-4651-b897-1ce978950acc,2dd83dc1-bf4d-4759-8b5d-beba82344866,3965012,4,51,0.733997,251,28,True,0.812204,...,469802,1854,29011,19297,0.348929,56705343,81738438,0.321917,True,91.439596
99999,b0319b22-e0e2-45bc-bb8c-457964d6c9c9,5dd4deb4-bc7d-4411-be3a-45d13730ebc2,436933,23,42,0.913652,262,4,False,0.609147,...,170163,40896,28085,1940,0.160300,47065243,93755759,0.242520,True,8.660436

In [2]:
from sklearn.tree import DecisionTreeRegressor

column_to_test = 'virality_score'
model = DecisionTreeRegressor()
number_of_models = 10

data = df.copy()

data = data.filter(items=[
'reach',
'impressions',
'non_follower_reach_ratio',
'explore_page_boost',
column_to_test,
])

print(df.columns)
data

Index(['reel_id', 'creator_id', 'creator_followers', 'posting_time',
       'reel_length_sec', 'hook_strength_score', 'caption_length',
       'hashtags_count', 'trending_audio', 'audio_popularity_score',
       'video_quality_score', 'editing_quality_score', 'avg_watch_time_sec',
       'retention_rate', 'completion_rate', 'rewatch_rate', 'likes',
       'comments', 'shares', 'saves', 'engagement_rate', 'impressions',
       'reach', 'non_follower_reach_ratio', 'explore_page_boost',
       'virality_score'],
      dtype='str')

,reach,impressions,non_follower_reach_ratio,explore_page_boost,virality_score
0,39007279,75968410,0.960121,False,82.843160
1,84132612,90722120,0.909716,False,60.256519
2,82019789,75215994,0.101694,True,0.483295
3,89513213,32759775,0.900505,False,21.686033
4,25073380,12315042,0.589176,True,46.046599
...,...,...,...,...,...
99995,47248377,92834444,0.484767,False,89.025863
99996,91497041,79691074,0.360169,False,86.450634
99997,20412833,99281430,0.408280,True,43.480384
99998,81738438,56705343,0.321917,True,91.439596
99999,93755759,47065243,0.242520,True,8.660436

In [3]:
from sklearn.model_selection import train_test_split

X = data.drop(columns=[column_to_test])
y = data[column_to_test]

print("Features (X):")
print(X)
print("Target (y):")
print(y)

Features (X):
          reach  impressions  non_follower_reach_ratio  explore_page_boost
0      39007279     75968410                  0.960121               False
1      84132612     90722120                  0.909716               False
2      82019789     75215994                  0.101694                True
3      89513213     32759775                  0.900505               False
4      25073380     12315042                  0.589176                True
...         ...          ...                       ...                 ...
99995  47248377     92834444                  0.484767               False
99996  91497041     79691074                  0.360169               False
99997  20412833     99281430                  0.408280                True
99998  81738438     56705343                  0.321917                True
99999  93755759     47065243                  0.242520                True

[100000 rows x 4 columns]
Target (y):
0        82.843160
1        60.256519
2         0.483295
3        21.686033
4        46.046599
           ...
99995    89.025863
99996    86.450634
99997    43.480384
99998    91.439596
99999     8.660436
Name: virality_score, Length: 100000, dtype: float64

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_train_pred = model.predict(X_train)

training_result = pd.DataFrame({'Actual': y_train, 'Predicted': y_train_pred})
test_result = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})

training_accuracy = model.score(X_train, y_train)
print(f"Training Accuracy: {training_accuracy}")
print(training_result)

test_accuracy = model.score(X_test, y_test)
print(f"Test Accuracy: {test_accuracy}")
print(test_result)

Training Accuracy: 1.0
          Actual  Predicted
66637  53.039238  53.039238
635    39.682533  39.682533
53895  44.673060  44.673060
5691   43.870524  43.870524
35704  15.516753  15.516753
...          ...        ...
35973  70.576082  70.576082
26231   7.280606   7.280606
13770  53.228179  53.228179
96837  50.688444  50.688444
26205  18.704790  18.704790

[80000 rows x 2 columns]
Test Accuracy: -1.0456255884887313
          Actual  Predicted
3968    5.694575  77.428523
63737  19.238147  14.570818
67686  59.381493  15.359022
49207  97.244011  39.481073
98112  91.899440  93.731586
...          ...        ...
56835  27.274691  90.139476
16050  63.289518  99.924442
77005  42.761415  10.908857
7847   33.296960  95.400254
53718  11.474069  95.400827

[20000 rows x 2 columns]