In [250]:
import pandas as pd

df = pd.read_csv('../data/instagram_reels_clean.csv')

column_to_test = 'virality_score'

df = df.drop(columns=[
'post_id',
'shortcode',
'views',
'likes',
'comments',
'creator_handle',
'timestamp_utc',
'caption',
'engagement_rate_pct',
'virality_tier'
])

df

,video_duration_sec,caption_word_count,hashtag_count,niche,virality_score
0,51.4,2,4,Technology & Gadgets,88.2
1,100.7,116,3,Entertainment,98.1
2,50.7,12,3,Fitness & Lifestyle,98.1
3,40.7,40,0,Entertainment,69.2
4,37.2,4,1,Technology & Gadgets,97.2
...,...,...,...,...,...
83,44.5,41,4,Technology & Gadgets,83.5
84,72.9,113,0,Personal Finance,73.0
85,57.6,66,0,Personal Finance,58.6
86,89.9,81,5,Food & Cooking,61.0
87,35.9,101,3,Personal Finance,55.4

In [251]:
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

model = make_pipeline(
    ColumnTransformer(
        transformers=[
            ('encoder', OneHotEncoder(handle_unknown="ignore", sparse_output=False), ['niche']),
        ]
    ),
    StandardScaler(),
    #LogisticRegression()
    KNeighborsRegressor(n_neighbors=5)
)

In [252]:
X = df.drop(columns=[column_to_test])
y = df[column_to_test]

In [253]:
from sklearn.model_selection import cross_val_score, train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model.fit(X_train, y_train)

cross_val_scores = cross_val_score(model, X, y, cv=5)

test_score = model.score(X_test, y_test)

print(f"CV Accuracy: {cross_val_scores.mean()}")
print(f"CV Standard deviation: {cross_val_scores.std()}")

print(f"Test Accuracy: {test_score}")

predictions = pd.DataFrame({
  "actual": y_test,
  "predicted": model.predict(X_test)
})
predictions

CV Accuracy: -0.5449260982275235
CV Standard deviation: 0.561889872580301
Test Accuracy: 0.45616294096620746

    actual  predicted
15    95.1      89.88
64    74.6      82.44
4     97.2      82.44
11    94.5      89.88
9     83.2      82.44
31    71.2      89.88
68    86.3      82.44
86    61.0      71.02
29    91.1      89.88
13    67.3      64.98
69    60.3      70.86
35    65.5      71.02
0     88.2      82.44
56    72.2      82.44
25    81.2      89.88
60    66.6      64.98
65    62.2      82.44
76    61.1      64.98