In [114]:
import pandas as pd

df = pd.read_csv('../data/instagram_reels_clean.csv')

df

,post_id,shortcode,creator_handle,caption,timestamp_utc,video_duration_sec,views,likes,comments,caption_word_count,hashtag_count,niche,engagement_rate_pct,virality_score,virality_tier
0,3971607901016940165,Dcd_FfvP96F,techburner,Robot Phone🤯\n\n#robot #ai #smartphone #reels,2026-08-25 15:44:22+00:00,51.4,3198411,224480,1073,2,4,Technology & Gadgets,7.05,88.2,Viral Hit
1,3968684083096105119,DcTmSWGsLCf,ranveerallahbadia,This is genuinely the happiest phase of my lif...,2026-08-21 14:55:37+00:00,100.7,2969964,284682,583,116,3,Entertainment,9.60,98.1,Viral Hit
2,3921292129996925127,DZrOmqVAGjH,beerbiceps,World Cup begins today for most of us ❤️🇵🇹\n.\...,2026-06-17 05:37:39+00:00,50.7,1982315,371478,3853,12,3,Fitness & Lifestyle,18.93,98.1,Viral Hit
3,3957069018352961979,DbqVU6Gocm7,onepercentclubshow,Everyone thinks owning an Airbnb is easy passi...,2026-08-05 14:17:47+00:00,40.7,1606642,47697,304,40,0,Entertainment,2.99,69.2,High Reach
4,3972244393712137742,DcgPzrwP7YO,techburner,IPhone vs Robot Phone🔥\n\n#reels,2026-08-26 12:48:43+00:00,37.2,1588449,168964,350,4,1,Technology & Gadgets,10.66,97.2,Viral Hit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,3975893922953744925,DctNnUuStId,techburner,Get a free game with selected Intel powered la...,2026-08-31 13:39:56+00:00,44.5,51709,4614,609,41,4,Technology & Gadgets,10.10,83.5,Viral Hit
84,3956310956626342814,Dbno9qGsvOe,financewithsharan,Some of India's biggest multibagger stocks sho...,2026-08-04 13:11:39+00:00,72.9,49012,2281,1367,113,0,Personal Finance,7.44,73.0,High Reach
85,3975706540088823856,DcsjAi1MRAw,financewithsharan,Can math actually beat the market? 📈\n\nQuant ...,2026-08-31 07:27:11+00:00,57.6,47538,1836,6,66,0,Personal Finance,3.87,58.6,High Reach
86,3981564284268470224,DdBW58ONF_Q,kabitaskitchen,Wahi paratha per zyada nutritions ke sath 🤩\n\...,2026-09-08 09:26:16+00:00,89.9,23971,1203,33,81,5,Food & Cooking,5.16,61.0,High Reach
87,3981680893259583747,DdBxa0zspED,financewithsharan,Where does your salary actually go every month...,2026-09-08 13:18:09+00:00,35.9,8919,353,69,101,3,Personal Finance,4.73,55.4,High Reach

In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import LabelEncoder, StandardScaler

column_to_test = 'virality_score'

model = make_pipeline(
    StandardScaler(),
    LinearRegression() 
)

df = df.drop(columns=[
'post_id',
'shortcode',
'views',
'likes',
'comments',
'creator_handle',
'timestamp_utc',
'caption',
'engagement_rate_pct',
'virality_tier'
])

df['niche'] = LabelEncoder().fit_transform(df['niche'])

df

,video_duration_sec,caption_word_count,hashtag_count,niche,virality_score
0,51.4,2,4,4,88.2
1,100.7,116,3,0,98.1
2,50.7,12,3,1,98.1
3,40.7,40,0,0,69.2
4,37.2,4,1,4,97.2
...,...,...,...,...,...
83,44.5,41,4,4,83.5
84,72.9,113,0,3,73.0
85,57.6,66,0,3,58.6
86,89.9,81,5,2,61.0
87,35.9,101,3,3,55.4

In [116]:
X = df.drop(columns=[column_to_test])
y = df[column_to_test]

In [117]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

result = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
accuracy = model.score(X_test, y_test)

print(f"Accuracy: {accuracy}")
print(result)

Accuracy: -0.6518683788089652
    Actual  Predicted
72    70.3  72.540006
36    61.6  72.442405
33    64.8  75.749931
0     88.2  78.145288
84    73.0  60.587667
68    86.3  76.064399
15    95.1  81.642760
18    87.7  85.455611
80    75.3  76.187700
50    69.5  76.941708
1     98.1  65.915889
86    61.0  66.801977
22    75.8  88.042146
76    61.1  61.871891
49    76.0  61.215224
45    89.0  61.106169
75    75.2  70.881884
34    59.5  93.174228