In [46]:
import pandas as pd
df = pd.read_csv('../data/youtube_shorts_performance_dataset.csv')

df

,video_id,title,duration_sec,hashtags_count,views,likes,comments,shares,upload_hour,category
0,vid_1000,Short Video #0,43,9,198775,21933,3228,400,8,Tech
1,vid_1001,Short Video #1,56,2,290336,20063,3719,1942,16,Comedy
2,vid_1002,Short Video #2,33,6,264206,37032,3228,1817,7,Food
3,vid_1003,Short Video #3,19,9,85076,27269,2371,980,1,Lifestyle
4,vid_1004,Short Video #4,47,8,90780,8041,2891,1109,23,Tech
...,...,...,...,...,...,...,...,...,...,...
295,vid_1295,Short Video #295,15,3,248940,23810,488,1247,12,Tech
296,vid_1296,Short Video #296,32,4,366340,29586,46,1548,8,Travel
297,vid_1297,Short Video #297,29,3,434027,6471,3359,1069,21,Comedy
298,vid_1298,Short Video #298,54,4,318623,6459,4873,1690,14,Food
299,vid_1299,Short Video #299,27,6,217464,40731,4806,1136,13,Tech

In [47]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder

column_to_test = 'engagement'
model = LinearRegression()

df["category"] = LabelEncoder().fit_transform(df["category"])
df["engagement"] = df.apply(lambda row: 100*(row["likes"] + row["comments"]*5 + row["shares"] * 10)/row["views"], axis=1)

df = df.drop(columns=[
"video_id",
"title",
"views",
"likes",
"comments",
"shares"
])

df

     duration_sec  hashtags_count  upload_hour  category  engagement
0              43               9            8         4   21.166143
1              56               2           16         0   20.003720
2              33               6            7         2   27.002415
3              19               9            1         3   57.506230
4              47               8           23         4   36.997136
..            ...             ...          ...       ...         ...
295            15               3           12         4   15.553949
296            32               4            8         5   12.364470
297            29               3           21         0    7.823476
298            54               4           14         2   14.978203
299            27               6           13         4   35.003955

[300 rows x 5 columns]

In [34]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=[column_to_test])
y = df[column_to_test]

print("Features (X):")
print(X)
print("Target (y):")
print(y)

Features (X):
     duration_sec  hashtags_count  upload_hour  category
0              43               9            8         4
1              56               2           16         0
2              33               6            7         2
3              19               9            1         3
4              47               8           23         4
..            ...             ...          ...       ...
295            15               3           12         4
296            32               4            8         5
297            29               3           21         0
298            54               4           14         2
299            27               6           13         4

[300 rows x 4 columns]
Target (y):
0      4207300
1      5807800
2      7134200
3      4892400
4      3358600
        ...
295    3872000
296    4529600
297    3395600
298    4772400
299    7612100
Name: engagement, Length: 300, dtype: int64

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

result = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})

accuracy = model.score(X_test, y_test)
print(f"Accuracy: {accuracy}")

print(result)

Accuracy: -0.014410847863948195
      Actual     Predicted
110  3801800  4.693700e+06
248  4528900  4.750480e+06
105  2209100  4.637657e+06
123  6547000  4.755237e+06
64   1065200  4.847214e+06
215  5599400  5.081467e+06
6    3069400  4.516784e+06
191  3660400  5.048414e+06
183  3388300  4.749957e+06
180  2645600  4.612755e+06
297  3395600  4.924866e+06
190  7264000  4.630720e+06
264  4916200  4.522374e+06
109  2885100  4.779507e+06
234  5408500  4.835015e+06
14   5956900  5.010780e+06
295  3872000  4.409874e+06
12   2575400  5.000296e+06
34   4247300  4.355161e+06
100  2579400  4.562438e+06
146  6080800  4.439199e+06
55   5980100  4.753538e+06
154  4207600  4.270089e+06
7    2292000  4.341602e+06
165  3865300  4.778510e+06
29   7107800  4.764389e+06
46   5236800  5.012817e+06
257  5767600  4.489743e+06
1    5807800  4.979957e+06
177  4669600  4.917914e+06
117  4315800  4.627112e+06
52   3554800  5.167337e+06
240  3668900  5.099067e+06
94   5414300  4.694725e+06
236  6423500  4.590687e+06
253  5018400  4.963507e+06
19   2173700  4.389759e+06
258  3009600  4.520719e+06
125  8000200  4.281994e+06
61   2360300  4.283998e+06
186  5940400  4.355695e+06
207  4719300  4.354840e+06
17   2962300  4.376816e+06
68   1324200  4.538822e+06
90   5569400  4.607325e+06
162  5984300  5.123153e+06
228  7100700  5.029418e+06
208  4415300  4.219093e+06
170  4027900  4.458675e+06
239  3142000  4.383182e+06
118  3273400  5.145512e+06
211  3573800  4.165885e+06
285  3486400  4.898941e+06
201  6592100  5.030614e+06
98   2707700  4.439775e+06
70   2866000  4.224342e+06
21   4580600  4.663197e+06
155  4096000  4.110987e+06
82   4247200  4.835410e+06
77   4954900  4.316473e+06